library/koji_tag.py

Koji does not make this clear, but string name identifiers are allowed in this
field. Using a list results in an error.
#

Change "perm" type to "str"

---

library/koji_cg.py
library/koji_host.py
library/koji_tag.py
library/koji_target.py

This allows errors to be handled at the task level, rather than halting
execution immediately.

Wrap exceptions with AnsibleError

---

library/koji_tag.py
library/koji_target.py

More information in the error output and some cryptic messages
prevented. Not an ideal solution—it would be better to be able to track
the progress of ensure_tag somehow.

Minor improvements to module error handling

---

library/koji_tag.py

Apparently `addTag` doesn't accept permission strings. Unfortunately, it
looks like the `koji` client does the same thing here. Hopefully this
naïve caching trick reduces the impact.

Look up string permissions

---

library/koji_target.py

Apparently `koji` uses `targetinfo` to refer to just the name of a
target, sometimes. Probably a documentation bug.

Use name as targetinfo for build target edits

---

library/koji_tag_inheritance.py

Koji does not allow us to have multiple parents with the same priority.
When we set a tag's inheritance, we must delete any rules with the existing priority first.

koji_tag_inheritance: replace any existing priorities

---

library/koji_tag.py
library/koji_tag_inheritance.py
tests/test_koji_tag_inheritance.py

For inheritance, old and new are displayed in the style of the Koji
CLI's `taginfo` command.
Additionally, in check mode, if a parent tag doesn't exist, a line
is added to the output, but no error is raised.

More elaborate difference reporting in check mode

---

library/koji_tag.py

Without this, missing parents will cause the inscrutable error:
```TypeError: 'NoneType' object has no attribute '__getitem__'```

Allow check mode to continue beyond missing parents

---

library/koji_tag.py

Avoid overriding perms, arches, and other types which editTag2 incorrectly
translates to strings as "None".

Skip NoneType attribute values

---

library/koji_tag_inheritance.py

Expand the description of the `maxdepth` parameter. In particular, call out what happens if the user does not specify any `maxdepth` value.

koji_tag_inheritance: more description for maxdepth

---

README.rst

There is some debate about including bazillion Ansible modules in Ansible itself. Personally I still think it's fine to pursue merging koji-ansible into Ansible, but we may want to look at Collections as an intermediate step.

README: mention Ansible Collections as a distribution mechanism

---

library/koji_tag.py

We accidentally duplicated the `locked` documentation. Remove the duplicate.

koji_tag: remove duplicate "locked" documentation

---

library/koji_tag.py

Document the ways that the ordering matters for the `arches` parameter.

koji_tag: document "arches" ordering

---

library/koji_tag_inheritance.py
tests/test_koji_tag_inheritance.py

When deleting an inheritance relationship, we should not make the user specify the relationship's `priority`. It's easier for the user to just specify the `child_tag` and `parent_tag`.

koji_tag_inheritance: "state: absent" does not require "priority"

---

README.rst
library/koji_host.py

We called `addHostToChannel()` with `create=True`, but we didn't call this out in the documentation. Add a description of this behavior to the module docs and readme.

koji_host: document automatic channel creation

---

tests/test_common_koji.py

On Python 3, the error message string is in the "`.value`" attribute.
Assert that the `.value` attribute has the string we need.

tests: py3 compat for error message checking

---

.travis.yml
tox.ini

Add Python 3.6 to the test matrix for every branch and pull request.

enable py36 testing in tox and Travis CI

---

library/koji_tag.py
library/koji_tag_inheritance.py
module_utils/common_koji.py
tests/test_koji_tag_inheritance.py

This patch adds support for the following properties of inheritance
links:
* `intransitive`
* `maxdepth`
* `noconfig`
* `pkg_filter`
Additionally, it improves the human-readable output for inheritance link
changes, displaying a summary of the past and current (or current and
future, in the case of check mode) inheritance on the tag (`koji_tag`
only), and showing the additional flags and extra details for the
features listed above in the same format as the koji CLI client.

Improve support for inheritance links between tags

---

tests/integration/koji_tag/main.yml
tests/integration/koji_tag/maxdepth-2.yml
tests/integration/koji_tag/maxdepth-3.yml
tests/integration/koji_tag/maxdepth-4.yml
tests/integration/koji_tag/maxdepth-5.yml

We've implemented "maxdepth" for `koji_tag`. Run more integration tests to exercise this feature.

tests: more maxdepth integration tests for koji_tag

---

tests/integration/koji_archivetype/basic-1.yml
tests/integration/koji_archivetype/main.yml

Upstream Koji has the `addArchiveType` RPC now, so we can run this integration test.
https://pagure.io/koji/pull-request/1149

add koji_archivetype integration tests

---

requirements.txt

Ansible 2.7 is not really supported any more, and it's painful to always bump this number. Let's test with the latest.

requirements.txt: unpin Ansible

---

README.rst
library/koji_archivetype.py

Document the Koji version that supports the `addArchiveType` RPC.

koji_archivetype: addArchiveType is in Koji 1.20

---

library/koji_cg.py

The Koji client's Exceptions work a little bit differently in py2 vs py3.
On Python 2, it's fine to catch the exception from the main koji module.
On Python 3, you must catch the exception from our specific profile module, not the main "koji" one.

koji_cg: py3 compat for exception handling

---

README.rst
library/koji_cg.py
tests/test_koji_cg.py

Koji 1.19 introduced a new `listCGs` RPC. Update our `koji_cg` module to use `listCGs`, falling back to the old try/catch method if the hub is too old and `listCGs` is unavailable.
Add unit tests for `koji_cg`.

koji_cg: use the new "listCGs" method

---

library/koji_tag.py

Each dictionary in the `external_repos` list must have a key named `repo`. Update the documentation to describe this `repo` key.

koji_tag: document external_repos "repo" key

---

.travis.yml
README.rst
tox.ini

Run the unit tests with pytest-cov and submit the results to coveralls.io.
This allows us to track overall code coverage metrics over time and identify the specific areas of the code that are under-tested.

submit code coverage metrics to coveralls.io

---

tests/test_koji_tag.py

Test two use-cases for `koji_tag`'s `ensure_external_repos()` method:
1. Adding two repos where none exist.
2. Adding one repo where one already exists.
These tests will make it easier to refactor this method safely.

tests: add unit test for ensure_external_repos

---

README.rst

This was pointing at my work-in-progress "coverage" branch, and we really want to point it to the default branch (master).

README: fix coveralls badge URL

---

library/koji_tag.py
tests/integration/koji_tag/main.yml
tests/integration/koji_tag/maxdepth-6.yml

In some cases, it is not trivial to make Ansible set a variable to "`None`" using Jinja filters. If the user does not enable Ansible's "`jinja2_native`" setting, variables are often set to empty strings `""` instead of "`None`".
The `koji_tag` module passes the empty string directly to the `setInheritanceData` RPC, which passes it into psychopg, which raises an error on the hub.
There are ways to work around this: enable "`jinja2_native`" locally, or use the "`default(omit)`" Jinja filter. These workarounds are complex and surprising to new users.
For usability, treat empty maxdepth strings `""` as `None`.
This new `maxdepth-6.yml` integration test triggers the psychopg error without the corresponding `koji_tag.py` change.

koji_tag: treat maxdepth empty strings as None

---

library/koji_tag.py
tests/integration/koji_tag/main.yml
tests/integration/koji_tag/maxdepth-7.yml

In some cases, it is not trivial to make Ansible set a variable to an integer using Jinja filters. If the user does not enable Ansible's "jinja2_native" setting, variables are often set to strings instead of ints.
The describe_inheritance() method always requires an integer, so it crashes when we pass in a string instead.
Commit ddf233dcc7efa79d705da7c35d7a8a4e874403f6 makes empty strings "`None`". This change builds on that to make non-empty strings integers.
The new maxdepth-7.yml integration test crashes in the format string in `describe_inheritance()` without this change.

koji_tag: non-empty maxdepth strings should be ints

---

tests/integration/koji_archivetype/main.yml
tests/integration/koji_btype/main.yml
tests/integration/koji_cg/main.yml
tests/integration/koji_host/main.yml
tests/integration/koji_tag/main.yml
tests/integration/koji_tag_inheritance/main.yml
tests/integration/koji_target/main.yml

Explicitly listing every test file is tedious and error-prone.
Auto-discover and include every test in each playbook's directory.

tests: autodiscover integration tests

---

library/koji_cg.py
tests/test_koji_cg.py

Add unit tests for the `list_cgs()` method.
This uncovered a bug where Python 3 crashes if we're querying an old Koji hub that lacks `listCGs`, so this PR includes a fix for that.

koji_cg: py3 compat and test coverage for list_cgs()

---

utils/generate-playbook

Invoke `python3` from `$PATH`, rather than invoking the system-wide `/usr/bin/python3`.
This makes it easier to use this script in a virtualenv.

generate-playbook: use virtualenv-friendly shebang

---

utils/generate-playbook

The default profile is "koji", not "cbs".
Update the `--help` text to match the code.

generate-playbook: fix help message for default profile

---

library/koji_tag.py
tests/test_koji_tag.py

If a user specifies two external repositories with the same name or priority, we should bail out early.

koji_tag: validate that each external-repo name and priority is unique

---

utils/generate-playbook

Prior to this change, when we tried to invoke the new multicall interface, we would crash on older Koji client versions.
Verify that our session's multicall attribute is callable, and if it is not, print an error message to the user.

generate-playbook: graceful error on older Koji client versions

---

build-collection

Prior to this change, we could not load published Ansible Collection versions because those require a slightly different import path.
`from ansible.module_utils import common_koji` works fine when running the modules directly from a Git clone, but we must import the common\_koji module from a different path when we load it as part of an Ansible Collection:
```
from ansible_collections.ktdreyer.koji_ansible.plugins.module_utils import common_koji
```

build-collection: alter common_koji import paths

---

README.rst

The role and collection installation for dependencies is done in
separate steps. This should be called out in the readme.

Role and collection install

---

library/koji_external_repo.py
library/koji_tag.py
library/koji_tag_inheritance.py

The import of display fails for containers when python calls getpwuid ()
which will return a KeyError.

Removing ansible.utils.display import

---

tests/integration/apache.conf
tests/integration/setup.sh

`koji-ssl-admin` now generates a `.chain.crt` file suitable for Apache.
We don't need to concatenate the HTTP server certificate and CA certificate ourselves.

tests: use koji-ssl-admin's .chain.crt file

---

library/koji_archivetype.py
library/koji_btype.py
library/koji_call.py
library/koji_cg.py
library/koji_host.py
library/koji_tag.py
library/koji_tag_inheritance.py
library/koji_target.py
library/koji_user.py

Most of the modules had at least one YAML syntax error. Fix all the syntax errors.
With this change, "ansible-doc" can parse each of the modules.

fix YAML syntax in documentation

---

library/koji_tag.py
tests/integration/koji_tag/inheritance-3.yml
tests/test_koji_tag.py

This change separates inheritance input normalization from parent/child
tag ID determination. It also adds a normalization process to priority
(always interpret as an integer).
Includes a unit test to check that string priority inputs function the
same as integer priority inputs, and an integration test to verify that
a string priority input will not be detected as a change.

koji_tag: inheritance input normalization

---

tests/integration/koji_target/delete-1.yml

Verify that we can delete a target from a hub.
This uses "state: absent" with "build_tag" and "dest_tag" parameters since the argument spec requires those parameters at the moment. A future PR will change the argument spec so that we don't have to set "build_tag" and "dest_tag" with "state: absent".

tests: add integration test for deleting a target

---

library/koji_target.py
tests/integration/koji_target/delete-1.yml

When deleting a Koji target, users should not have to specify `build_tag` or `dest_tag`.
Fixes: #132

koji_target: do not require build_tag and dest_tag when deleting

---

tests/test_koji_external_repo.py

Return the dict directly, rather than copying it to a variable and returning that.

tests: simplify kwargs fixture in test_koji_external_repo

---

library/koji_user.py
tests/test_koji_user.py

Document the behavior if a user does not set any permissions on a `koji_user`.
Fix the case where the user specifies an empty list to remove all permissions on an account.

koji_user: improve permission revocation

---

tests/test_koji_tag.py

Move the FakeSession() instantiation into a pytest fixture so that it is easier to use in each test that needs it.
This matches the pattern I've been using in some of the other unit tests.

tests: use pytest.fixture for session in test_koji_tag

---

tests/test_koji_tag.py

Refactor the tag_name variable to a pytest fixture, so that we do not copy-and-paste this for all tests.

tests: add tag_name pytest fixture to TestEnsureExternalRepos

---

tests/test_koji_tag.py

There is no such thing as a "CR" repository for EPEL 7. This was a bad copy & paste from "centos-7-cr".
Update these references to "epel-7" instead.

tests: remove references to "epel-7-cr"

---

tests/test_koji_tag.py

1) Update our `FakeSession` test fixture to keep track of our tag-repo associations. This allows us to read and assert `koji_tag.ensure_external_repos()`'s behavior on our fake session in each unit test.
2) Add a new unit test to ensure that `koji_tag.ensure_external_repos()` makes no changes when we expect no changes to be made.
3) Add a new unit test to ensure that that `koji_tag.ensure_external_repos()` can remove a repository.

tests: improve koji_tag.ensure_external_repos() unit tests

---

library/koji_tag.py
tests/integration/koji_tag/external-repos-3.yml
tests/test_koji_tag.py

Prior to this change, we would hit an error in the hub because we would try to add an external repo at the same priority as one that already exists.
Switch the order of operations so that we delete all the wrong repos from the hub and then add all the correct repos that are missing.
This change drops our use of `editExternalRepos`. It would be faster and idempotent to use that RPC instead of the pair of remove+add RPCs, however the `editExternalRepos` RPC silently resets `merge_mode` if the Koji hub is older than v1.21 (https://pagure.io/koji/issue/1857). Maybe we can find a better way to use `editExternalRepos` in the future.
This also moves our add/remove RPC loops to make those easier to test and refactor to multicalls later.

koji_tag: remove then add in ensure_external_repos

---

library/koji_tag.py

Improve the docstrings for the `ensure_packages()` and `ensure_groups()` methods.

koji_tag: better docstrings for "packages" and "desired_groups" parameters

---

library/koji_tag.py
tests/integration/koji_tag/external-repos-4.yml
tests/integration/koji_tag/external-repos-5.yml
tests/test_koji_tag.py

Add support for the new "merge_mode" setting for external repos.
For backwards compatibility, if the user does not set a "merge_mode" and the external repository already exists at the given priority, then Ansible will not edit the existing merge mode.
Fixes: #36 
Fixes: #127

koji_tag: add merge_mode support for external repos

---

README.rst

The koji-ansible CI system has moved from travsi-ci.org to travis-ci.com.

README: fix links to travis-ci.com

---

library/koji_host.py

The "`host_name`" parameter is a string, not an int.

koji_host: fix "host_name" docstring for ensure_channels()

---

library/koji_user.py

The "`name`" parameter is the name of a user, not a builder.

koji_user: fix "name" docstring for ensure_user()

---

library/koji_archivetype.py
library/koji_btype.py
library/koji_call.py
library/koji_cg.py
library/koji_external_repo.py
library/koji_host.py
library/koji_tag.py
library/koji_tag_inheritance.py
library/koji_target.py
library/koji_user.py

The default "type" for `AnsibleModule`'s `argument_spec` is "`str`". There is no need to specify it in our code.
Remove "`type='str'`" to simplify the code and make it easier to read.
Fixes: #121

remove "type='str'" from argument_specs

---

tests/test_koji_external_repo.py
tests/test_koji_tag.py
tests/test_koji_user.py

Most of the unit tests use a class named `FakeKojiSession`. Standardize on that class name across all unit tests.
Fixes: #160

tests: rename FakeSession -> FakeKojiSession

---

tox.ini

Prior to this change, `tox -e flake8` failed because I typo'd the name to the "`library`" directory.

tox: fix flake8 library path

---

library/koji_tag.py

This method is not necessary if we use the correct types for the type
property of the argument spec. We still need to check to see if the
argument is given before operating against it though.
Fixes #155
Signed-off-by: Andrew Schoen <aschoen@redhat.com>

remove the compound_parameter_present method from library.koji_tag

---

library/koji_archivetype.py
library/koji_btype.py
library/koji_call.py
library/koji_cg.py
library/koji_external_repo.py
library/koji_host.py
library/koji_tag.py
library/koji_tag_inheritance.py
library/koji_target.py
library/koji_user.py

The default `required` value for `AnsibleModule`'s `argument_spec` is `False`. There is no need to specify it in our code.
Remove the `required=False` settings. This simplifies the code and makes it easier to read.
Fixes: #122

remove "required=False" for argument_spec options

---

build-collection

Upload builds to Ansible Galaxy in a way that sorts the current master version above everything else that we've already uploaded.
Fixes: #168

build-collection: use 0.0.COMMIT_COUNT for versioning

---

tests/test_koji_host.py

Prior to this change, we were calling `ensure_host()` with an empty list for `krb_principal`. This parameter should be a `str` or `None`.
Fixes: #165

tests: fix ensure_host() krb_principal parameter

---

library/koji_tag.py
tests/integration/koji_tag/empty-strings-1.yml

As described in ddf233dcc7efa79d705da7c35d7a8a4e874403f6, Ansible's default `jinja2_native` setting is `False`, and when this is `False`, the `default(None)` filter evaluates to an empty string.
With the changes in 8f9f1c1aa59e8463ca8425636073633650061266, we failed to process parameters with empty strings.
Update the `inheritance` and `external_repos` checks to test for lists of empty strings and skip them.
Update the `packages` and `groups` argspecs to `raw` in order to restore the old behavior before 8f9f1c1aa59e8463ca8425636073633650061266.
Fixes: #175

koji_tag: gracefully handle empty strings for parameters

---

.travis.yml
tests/integration/setup.sh

Add a new integration test that uses Ansible prereleases from PyPI.
Fixes: #172

.travis.yml: test ansible prerelease

---

README.rst

Remove the instructions for pinning versions with Ansible Galaxy.  We're using a newer version scheme (07c16a07971659042393cd92c61a0f8ebd5e33f3), so Ansible will always pull the latest.

README: do not pin versions from Ansible Galaxy

---

tests/test_koji_host.py

Switch the `koji_host` unit tests to use pytest fixtures. This matches the other unit tests and makes it easier to write more `koji_host` tests.

tests: use pytest fixtures in koji_host tests

---

tests/integration/travisci.conf

The latest versions of Koji warn about the deprecated "ca" option in our Koji client profile. This option has been a no-op for years.
Remove it to silence the deprecation warning and make the test output easier to read.
Fixes: #177

tests: remove deprecated koji "ca" option

---

tests/test_koji_host.py

It's not realistic to add builder hosts with an empty arches list, because Koji admins will almost never add a host without specifying at least one arch.
Use `x86_64` in the unit tests.

tests: call ensure_host with non-empty arches

---

build-collection

Ansible 2.9's `ansible-galaxy` utility is strict about what versions it accepts. It only accepts versions that match `StrictVersion.version_re`.
To be compatible with the 2.9 version of `ansible-galaxy`, trim our collection version number to be the simple `0.0.X` format.
Ansible 2.10's `ansible-galaxy` utility respects the full SemVer specification, so this is not an issue on Ansible 2.10+. We can revert this change when we're ready to drop Ansible 2.9 support.
Fixes: #180

build-collection: remove git suffix

---

README.rst
library/koji_call.py

Playbook authors need to know the Koji API when using the `koji_call` module. Link to the Koji API documentation so this is easier to discover.

koji_call: link to Koji API documentation

---

tests/integration/koji_tag_inheritance/create-1.yml
tests/integration/koji_tag_inheritance/create-2.yml

This pull request adds integration tests to assert all the default and non-default settings for `koji_tag_inheritance`.
Fixes: #187

add integration tests for all koji_tag_inheritance settings

---

library/koji_tag.py

Document Ansible's behavior when the playbook author omits the `packages` key for the `koji_tag` module.

koji_tag: document omitting "packages" setting

---

library/koji_btype.py
tests/test_koji_btype.py

Instead of asking the hub for all configured btypes and filtering that list client-side, we can query the hub for the exact btype name.
Fixes: #103

koji_btype: query exact btype name

---

README.rst
library/koji_call.py
library/koji_target.py
tests/test_koji_call.py

Update the "Fedora 29" and "Fedora 30" references in the docs and unit tests to a modern Fedora version number. This keeps the docs and tests fresh and easier to understand.

update hard-coded Fedora versions to 32

---

README.rst
library/koji_tag_packages.py

Remove the wording that could imply `koji_tag_packages` might possibly work in conjunction with `koji_tag`.
Explain that `koji_tag_packages` does not touch any other packages in the tag, regardless of the method the administrator used to configure the package list.
Document an example scenario where a playbook author might use the `koji_tag_packages` module instead of `koji_tag`.

koji_tag_packages: improve description and document example use-case

---

library/koji_tag.py
tests/integration/koji_tag/anonymous-1.yml
tests/integration/setup.sh

Prior to this change, if a user ran a `koji_tag` task that managed packages or groups on a tag, we unconditionally called koji's `activate_session()` method.
This is bad for performance because it puts load on the hub when we might not need to authorize any changes. When users run check mode, we should never authenticate. (This also means we ought to let users run check mode without valid credentials.)
Move the `ensure_logged_in()` calls inside the "`if not check_mode`" conditions. Add a new integration test that uses check mode and an anonymous session. (Prior to the `koji_tag` change, this test would fail with an `AuthError`.)
Fixes: #200

koji_tag: do not require logins for check-mode

---

library/koji_tag.py

"repos" is a list. Update the docstring to reflect this.

koji_tag: update repos type in validate_repos() docstring

---

README.rst

Use the definite article when listing the settings `koji_tag` can manage.
The `koji_tag` module can manage multiple groups, and the parameter is "`groups`". Use the plural form for clarity.

README: grammer fixes for koji_tag summary

---

README.rst

Commit e50622a50c6b15e259a815d55022b77f00ac85cd updated all other Fedora references, but I missed one reference to Fedora 29 here. Update this one to Fedora 32 as well. With this change, the human-readable text matches the example Ansible task.

README: update hard-coded Fedora build tag number to 32

---

tests/integration/koji_host/kerberos-1.yml

Test creating a new host with a non-default `krb_principal`.

tests: integration test for koji_host krb_principal

---

tests/integration/apache.conf
tests/integration/ci.conf
tests/integration/functions.sh
tests/integration/koji_cg/basic-1.yml
tests/integration/koji_cg/revoke-1.yml
tests/integration/koji_tag/anonymous-1.yml
tests/integration/koji_tag/basic-1.yml
tests/integration/koji_tag_packages/basic-1.yml
tests/integration/koji_tag_packages/basic-2.yml
tests/integration/run.sh
tests/integration/setup.sh

I used the string "travisci" for the Koji profile name and default Koji username. Since we're not using Travis CI any more, replace these with generic names.
The Koji profile is now named "ci", and the Koji username is now "admin".

tests: remove references to travisci

---

README.rst
library/koji_archivetype.py
tests/integration/koji_archivetype/basic-1.yml
tests/test_koji_archivetype.py

From https://pagure.io/koji/issue/2575, the `deb` archivetype will be upstream by default in Koji 1.24.
Update the documentation to describe how to add OpenWrt's package files (`.opk files`) instead of Debian packages.
Switch the integration test to use `dsc` instead, since that is not in Koji upstream.

archivetype: remove "deb" example and test

---

README.rst
library/koji_tag_inheritance.py

Rather than using `koji_tag_inheritance`, it's possible to have MBS operate on a dedicated tag instead. Document this in the README and the module inline docs.

koji_tag_inheritance: document alternative method for MBS

---

.github/workflows/tests.yml
build-collection

When a GitHub Action runner checks out a non-master branch for testing, it checks out GitHub's magic "merge" ref. For example:
```
git checkout --progress --force refs/remotes/pull/192/merge
```
This puts the repository into a detached HEAD state. This means that we cannot search `HEAD` for `--max-parents=0`, because Git will simply return the sha we've checked out. This problem means that `COMMIT_COUNT` is always `-1` for pull requests and VERSION is always `0.0.-1`.
GitHub Action runners have a `GITHUB_BASE_REF` environment variable with the name of a pull request base branch. If that is defined, use that to discover the root commit of the base branch. This fixes the `COMMIT_COUNT` calculation for pull requests.

build-collection: fix VERSION for non-master tests

---

README.rst
library/koji_call.py
library/koji_target.py
tests/test_koji_call.py

Update the "Fedora 32" references in the docs and unit tests to a modern Fedora version number. This keeps the docs and tests fresh and easier to understand.

update hard-coded Fedora versions to 34

---

tests/integration/koji_host/basic-1.yml

With [Koji commit bc2a51350db2c40af31ed8a9f9a2bda834202d91](https://pagure.io/koji/c/bc2a51350db2c40af31ed8a9f9a2bda834202d91), `listChannels` now treats strings as hostnames, rather than treating them as host ID numbers.
Update the integration test suite to pass the builder hostname instead of the ID so that the tests will continue to pass with the latest Koji Hub code.
Fixes: #224

pass hostname to listChannels

---

build-collection
meta/runtime.yml

Ansible Galaxy now requires all collections to have a `meta/runtime.yml` file with `requires_ansible`. I'm choosing `2` because most of the v2 releases should work.

add meta/runtime.yml

---

tests/integration/apache.conf

GitHub Actions uses Ubuntu Focal now. We still need this `SSLProtocol` workaround for python-requests v2.22.0, though.

test: update SSLProtocol comment for Ubuntu Focal

---

tests/integration/setup.sh

`koji-ssl-admin` creates this combined SSL cert file automatically now.

tests: do not concatenate user SSL cert

---

tests/integration/koji_tag_packages/basic-1.yml
tests/integration/koji_tag_packages/basic-2.yml

Add titles to the integration tests to describe what each test does.
Change the `basic-2` test to operate on a unique tag name rather than re-using the tag from the `basic-1` test.

tag_packages: integration test cleanups

---

tests/test_koji_tag.py

Improve `getTag` fake method to take integers and to return `None` if `strict=False`.

koji_tag: improve fake getTag method in tests

---

tests/test_koji_tag_packages.py

`listPackages` in Koji v1.25+ takes a `with_owners` parameter. Accept this parameter in the `FakeKojiSession` in the test suite.
The test suite currently mocks `session.listPackages()` with a `Mock()` object rather than using `FakeKojiSession()`, so this does not affect the test runs yet. However, it's important to make this more robust for when we switch over to using `FakeKojiSession()`.

tag_packages: handle listPackages' with_owners arg in tests

---

library/koji_tag.py
tests/integration/koji_tag/blocked-packages-1.yml
tests/test_koji_tag.py

Please note: if you start using the new `blocked_packages` parameter with `koji_tag`, Ansible will *unblock* any blocked packages that you do not list here. If you miss packages in the list, you could unintentionally undo the work that admins did manually in the past. Quoting the docs: 
> if you have already manually blocked packages with `koji block-pkg`, you may want to omit this setting in Ansible until you've captured the exact list of already-blocked packages in Ansible.
Fixes: #242

koji_tag: add blocked_packages parameter

---

requirements.txt

Ansible 5.0.0 requires Python 3.8. For Python 3.7 and older, pin to the latest Ansible 4 version.

requirements.txt: pin to Ansible 4 on old python versions

---

.mergify.yml

GitHub does this automatically now, faster than Mergify can do it.  Remove this setting to avoid Mergify showing errors when trying to delete non-existent branches.

mergify: remove "delete branch" setting

---

.mergify.yml

The old configuration is deprecated, https://blog.mergify.com/strict-mode-deprecation/

mergify: use queues instead of strict mode

---

tests/integration/setup.sh

`listPackages` is broken in master, see https://pagure.io/koji/issue/3193
Revert this when master is working again.

clone forked koji for listPackages fix

---

library/koji_tag_inheritance.py
tests/integration/koji_tag_inheritance/update-2.yml

Prior to this change, `koji_tag_inheritance` failed to edit attributes on individual existing inheritance relationships if the edits did not change the parent tag's `priority` value.
The problem is that clients cannot call `setInheritanceData` with two rules of the same parent + priority, even if the first rule uses `"delete link"`. Instead, clients should simply define one new rule, and it will overwrite the current one for that priority.
Add an integration test to cover this scenario.
Fixes: #258

tag_inheritance: fix setInheritanceData for non-priority changes

---

tests/integration/setup.sh

We can go back to using master again now that [my PR](https://pagure.io/koji/pull-request/3196) is merged.
This reverts commit 6e5db63165bc6c41594f5f76c00c83cbdb14d6ed (https://github.com/ktdreyer/koji-ansible/pull/257)

Revert "clone forked koji for listPackages fix"

---

library/koji_tag.py
tests/integration/koji_tag/basic-1.yml

Fix the diff data in ensure_packages of koji_tag module
We should set the current_settings before checking if the package exist, otherwise the diff data is wrong when packages are updated.
JIRA: CWFCONF-2404

Fix the diff data for ensure_packages in koji_tag module

---

.github/workflows/tests.yml
tests/integration/apache.conf
tests/integration/setup.sh

The `ubuntu-latest` image no longer has `py27` or `py36` available. Pin to an older Ubuntu image for testing these older Python versions.
The `kojihub` code location has changed in Koji's Git. Update the tests to use the new location.

fix GitHub Actions tests

---

.mergify.yml

Commit 714cd57f94e2e76ee50d3fc4490bae4c4eac56b4 changed the names of our test results slightly. Update Mergify to recognize these new test names.

mergify: update for older ubuntu test matrix

---

.github/workflows/ansiblegalaxy.yml

With the switch to checkout v3 in commit c491621a4f339147e5016b37dd7fc2affcd77eed, `VERSION` is always `0.0.-1`.
Fetch the full history so that we properly calculate `VERSION` again.

github: fetch full git history

---

README.rst

Ansible Galaxy no longer supports the v2 REST API. Switch to v3.

README: update Galaxy badge URL
