- library/koji_tag.py
An empty value is coreced into a non-empty list: ['']
To avoid this, use the `raw` type and use isinstance() to ensure that
the parameter has the correct type.
This patch also moves inheritance and packages into separate functions,
to match external repositories.
Inspired by ansible/ansible#32367.
> Use "raw" instead of "list"/"dict" parameters

- README.rst
- library/koji_tag.py
> Add package group management

- README.rst
- library/koji_host.py
- tests/test_koji_host.py
> koji_host: Allow editing channels

- library/koji_tag_inheritance.py
- tests/test_koji_tag_inheritance.py
> Support maxdepth param for tag inheritance

- library/koji_tag.py
Koji treats group/package additions as a noop if they already exist on a
parent tag, so `koji_tag` would appear to always be making a change, even
when Koji would silently ignore it. This patch also ignores inherited
groups and packages when deciding what to add and remove.
> Allow inherited tag groups and tag group packages

- README.rst
Suggest to users how they can use the "koji list-history" command to find out changes that may have happened outside of Ansible.
> README: describe how to use "koji list-history"

- README.rst
Link to the Koji upstream project to make it clearer to casual readers who stumble on this project.
> README: link to koji upstream project

- .travis.yml
- tests/integration/ansible.cfg
- tests/integration/apache.conf
- tests/integration/functions.sh
- tests/integration/koji_btype/basic-1.yml
- tests/integration/koji_btype/main.yml
- tests/integration/koji_cg/basic-1.yml
- tests/integration/koji_cg/main.yml
- tests/integration/koji_host/basic-1.yml
- tests/integration/koji_host/main.yml
- tests/integration/koji_tag/basic-1.yml
- tests/integration/koji_tag/groups-1.yml
- tests/integration/koji_tag/groups-2.yml
- tests/integration/koji_tag/inheritance-1.yml
- tests/integration/koji_tag/inheritance-2.yml
- tests/integration/koji_tag/main.yml
- tests/integration/koji_tag/maxdepth-1.yml
- tests/integration/koji_tag_inheritance/create-1.yml
- tests/integration/koji_tag_inheritance/delete-1.yml
- tests/integration/koji_tag_inheritance/main.yml
- tests/integration/koji_tag_inheritance/update-1.yml
- tests/integration/koji_target/basic-1.yml
- tests/integration/koji_target/basic-2.yml
- tests/integration/koji_target/main.yml
- tests/integration/run.sh
- tests/integration/setup.sh
- tests/integration/travisci.conf
Bring up a basic Koji hub and run a series of playbooks against it.
> run integration tests against live Koji hub

- tests/integration/koji_cg/main.yml
- tests/integration/koji_cg/revoke-1.yml
Test the case of revoking access to a content generator.
> tests: add revocation test for koji_cg

- tests/integration/koji_tag/external-repos-1.yml
- tests/integration/koji_tag/external-repos-2.yml
- tests/integration/koji_tag/main.yml
Add integration tests for adding, removing, and updating external repos for a tag.
> tests: integration tests for adding/removing/updating external repos

- .travis.yml
- requirements.txt
- tests/test_common_koji.py
Test the `get_session()` and `describe_inheritance_rule()` methods.
> tests: add more unit tests for common_koji.py

- tests/test_koji_call.py
Add test coverage for more `koji_call` features.
> tests: improve tests for koji_call

- tests/test_koji_tag.py
Provide test coverage for koji_tag's `ensure_inheritance()` method.
> tests: add tests for ensure_inheritance()

- README.rst
- library/koji_tag.py
- module_utils/common_koji.py
- tests/test_common_koji.py
- utils/generate-playbook
This can query a live Koji instance and generate the Ansible playbook YAML to recreate some or all of the tags.
> add generate-playbook utility

- tests/integration/koji_tag/external-repos-2.yml
This name was a bad copy & paste. Correct the name to describe what this task is really doing.
> tests: correct external-repos-2 "change priority" task name

- README.rst
Walk through how to use this collection in an Ansible role.
> README: document how to use the collection in a role

- .travis.yml
- tests/integration/collection.sh
Build the Ansible Collection tarball artifact, install it, and read the inline docs for each module.
> test collection build process

- .travis.yml
Reduce the boilerplate copy & paste.
> .travis.yml: simplify configuration

- library/koji_target.py
GenericError: invalid type for id lookup: <type 'dict'>
Fixes: https://github.com/ktdreyer/koji-ansible/issues/128
Signed-off-by: Igor Raits <i.gnatenko.brain@gmail.com>
> Make removing target work

- library/koji_archivetype.py
- library/koji_btype.py
- library/koji_cg.py
- library/koji_external_repo.py
- library/koji_host.py
- library/koji_tag.py
- library/koji_tag_inheritance.py
- library/koji_target.py
- library/koji_user.py
Closes: https://github.com/ktdreyer/koji-ansible/issues/120
Signed-off-by: Igor Raits <i.gnatenko.brain@gmail.com>
> Use choices in argparsing

- README.rst
- library/koji_tag_packages.py
- tests/integration/koji_tag_packages/basic-1.yml
- tests/integration/koji_tag_packages/basic-2.yml
- tests/integration/koji_tag_packages/main.yml
- tests/test_koji_tag_packages.py
- tox.ini
This module allows for fine-grained control of tag packages.
Fixes issue #166
> adds a koji_tag_packages module

- .copr/Makefile
- .copr/ansible-collection-ktdreyer-koji-ansible.spec.in
- .gitignore
@tstellar asked if we could package this as an RPM, so here we go.
Add a spec file template and a Makefile for https://copr.fedorainfracloud.org/coprs/ktdreyer/koji-ansible/
> add RPM packaging

- tests/test_koji_host.py
Add unit test coverage for the `koji_host` module.
> tests: add unit tests for koji_host

- tests/test_koji_host.py
Collapse these two unit tests down into one test, since it's almost the same code.
> tests: parameterize check_mode for TestEnsureHostCreated

- .github/workflows/tests.yml
- tox.ini
Run unit tests with Python 3.9.
> add py39 to tox tests

- library/koji_host.py
- library/koji_user.py
- module_utils/common_koji.py
- tests/integration/koji_host/kerberos-1.yml
- tests/integration/koji_host/kerberos-2.yml
- tests/integration/koji_user/kerberos-1.yml
- tests/integration/koji_user/kerberos-2.yml
- tests/test_koji_host.py
- tests/test_koji_user.py
Thanks @ignatenkobrain for the initial implementation.
Fixes: #138
> koji_user/koji_host: Allow setting multiple krb_principals

- library/koji_tag.py
> tag: document inheritance parameter

- tests/integration/koji_tag/inheritance-2.yml
- tests/integration/koji_tag/inheritance-3.yml
- tests/integration/koji_target/delete-1.yml
Fix a few errors in the `koji_tag` inheritance integration tests.
> tests: fix koji_tag integration tests

- .github/workflows/tests.yml
- .mergify.yml
- tests/integration/functions.sh
- tests/integration/koji_archivetype/main.yml
- tests/integration/koji_btype/main.yml
- tests/integration/koji_cg/main.yml
- tests/integration/koji_host/main.yml
- tests/integration/koji_tag/main.yml
- tests/integration/koji_tag_inheritance/main.yml
- tests/integration/koji_tag_packages/main.yml
- tests/integration/koji_target/main.yml
- tests/integration/koji_user/main.yml
- tests/integration/main.yml.in
GitHub no longer supports running Python 2.7 natively.
> fix tests in GitHub Actions
